function carregamento() {
    alert("A PÁGINA FOI CARREGADA COM SUCESSO!\nCLIQUE NA LOGO PARA ADENTRAR NO HTML APÓS FECHAR ESSA MENSAGEM!\nALGUNS EVENTOS INCLUSOS NESTE HTML:\nONLOAD, ONMOUSEOVER, ONMOUSEOUT E ONCLICK. ")
}